name: Build and Deploy Frontend (from Vue repo)

on:
  repository_dispatch:
    types: [vue-build]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout server repo
        uses: actions/checkout@v4

      - name: Checkout Vue app repo
        uses: actions/checkout@v4
        with:
          repository: Kayausie/to-do-list
          ref: main
          path: webapp

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies and build Vue app
        working-directory: webapp
        run: |
          npm ci
          npm run build

      - name: Copy built files into server project
        run: |
          rm -rf ./dist
          mkdir -p ./dist
          cp -R webapp/dist/* ./dist/

      - name: Verify copied files
        run: |
          ls -la dist | head -20

      # Add your actual deploy step below (Azure, etc.)
